export const POSTS_FETCH_START = 'POSTS_FETCH_START';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POSTS_FETCH_ERROR = 'POSTS_FETCH_ERROR';

export const POSTS_SEARCH = 'POSTS_SEARCH';

export const SINGLE_POST_FETCH_START = 'SINGLE_POST_FETCH_START';
export const SINGLE_POST_FETCH_SUCCESS = 'SINGLE_POST_FETCH_SUCCESS';
export const SINGLE_POST_FETCH_ERROR = 'SINGLE_POST_FETCH_ERROR';

export const POST_EDIT_START = 'POST_EDIT_START';

export const POST_DELETE_START = 'POST_DELETE_START';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
